# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Zoe Jane
tagline:          'A Jekyll theme'
description:      'Music. Programming. Love. Life.'
url:              http://zoejane.net
baseurl:          /

author:
  name:           'Zoe Jane'
  url:            https://twitter.com/dadac123

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zoejane

# Gems
gems: [jekyll-paginate]