baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://zoejane.net" # the base hostname & protocol for your site
title: "Zoe Jane"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

# SEO 相关设置
description: "在这里填写你的网站描述"
author: "你的名字"

gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  hard_wrap: false

# 添加插件支持
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# 确保这些文件不被 Jekyll 处理
keep_files:
  - robots.txt
  - sitemap.xml
